version: "3"
services:
  frontend:
    build: .
    entrypoint: url-shortener frontend
    ports:
      - "5000:8080"
    links:
      - jaeger
      - shortener
    depends_on:
      - shortener
  shortener:
    build: .
    entrypoint: url-shortener shortener
    links:
      - jaeger
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "14269"
      - "5778:5778"
      - "14268:14268"
      - "14267"
      - "16686:16686"
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
